# Generated by Django 2.2 on 2021-06-03 12:54

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_dob', models.DateField(blank=True, default=datetime.date.today, verbose_name='Date')),
                ('emp_doj', models.DateField(blank=True, default=datetime.date.today, verbose_name='Date')),
                ('desig', models.CharField(blank=True, max_length=256)),
                ('depart', models.CharField(blank=True, max_length=256)),
                ('manager', models.BooleanField(choices=[(True, 'on'), (False, 'off')], default=False)),
            ],
            options={
                'db_table': 'Employee',
            },
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('emplyr_name', models.CharField(max_length=256, primary_key='true', serialize=False)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'Employer',
            },
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salary', models.PositiveIntegerField()),
                ('emplyr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
            ],
            options={
                'db_table': 'Salary',
            },
        ),
        migrations.CreateModel(
            name='Leaves',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_date_from', models.DateField(blank=True, default=datetime.date.today, verbose_name='Date')),
                ('leave_date_to', models.DateField(blank=True, default=datetime.date.today, verbose_name='Date')),
                ('descript', models.CharField(blank=True, max_length=256)),
                ('status', models.CharField(blank=True, max_length=32)),
                ('leaves_taken', models.PositiveIntegerField(blank=True, default=0)),
                ('emplyr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
            ],
            options={
                'db_table': 'Leaves',
            },
        ),
        migrations.CreateModel(
            name='LeaveAccrualPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('policy_name', models.CharField(blank=True, max_length=256)),
                ('descript', models.CharField(blank=True, max_length=256)),
                ('effective_after_no', models.PositiveIntegerField(blank=True)),
                ('eff_yorm', models.CharField(blank=True, max_length=32)),
                ('eff_from', models.CharField(blank=True, max_length=32)),
                ('ac_y_m', models.CharField(blank=True, max_length=32)),
                ('ac_date', models.PositiveIntegerField(blank=True)),
                ('ac_datm', models.PositiveIntegerField(blank=True)),
                ('ac_mth', models.CharField(blank=True, max_length=32)),
                ('ac_ndays', models.PositiveIntegerField(blank=True)),
                ('re_y_m', models.CharField(blank=True, max_length=32)),
                ('re_dat', models.PositiveIntegerField(blank=True)),
                ('re_datm', models.PositiveIntegerField(blank=True)),
                ('re_mth', models.CharField(blank=True, max_length=32)),
                ('cf', models.CharField(blank=True, max_length=32)),
                ('cf_meter', models.CharField(blank=True, max_length=32)),
                ('cf_u', models.PositiveIntegerField(blank=True)),
                ('cf_p', models.PositiveIntegerField(blank=True)),
                ('ex_y_m', models.CharField(blank=True, max_length=32)),
                ('ex_mth', models.PositiveIntegerField(blank=True)),
                ('ex_y', models.PositiveIntegerField(blank=True)),
                ('ovr_lmt', models.PositiveIntegerField(blank=True)),
                ('en_mtr', models.CharField(blank=True, max_length=32)),
                ('en_u', models.PositiveIntegerField(blank=True)),
                ('en_p', models.PositiveIntegerField(blank=True)),
                ('en_ml', models.PositiveIntegerField(blank=True)),
                ('emplyr_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee')),
            ],
            options={
                'db_table': 'LeaveAccrualPolicy',
            },
        ),
        migrations.AddField(
            model_name='employee',
            name='emplyr_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employer'),
        ),
        migrations.AddField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
