# Generated by Django 2.2 on 2021-06-03 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ac_date',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ac_datm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ac_mth',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ac_ndays',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ac_y_m',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='cf',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='cf_meter',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='cf_p',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='cf_u',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='descript',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='eff_from',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='eff_yorm',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='effective_after_no',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='en_ml',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='en_mtr',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='en_p',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='en_u',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ex_mth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ex_y',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ex_y_m',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ovr_lmt',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='policy_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='re_dat',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='re_datm',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='re_mth',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='re_y_m',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
