# Generated by Django 2.2 on 2021-06-03 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0002_auto_20210603_1409'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_app.Employee', unique=True),
        ),
    ]
