# Generated by Django 2.2 on 2021-06-04 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0004_auto_20210603_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveaccrualpolicy',
            name='ac_ndays_incre_decre',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
