# Generated by Django 2.2 on 2021-06-06 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0006_leaveaccrualpolicy_ex_ac_updt_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaveaccrualpolicy',
            name='ex_ac_updt_list',
            field=models.CharField(blank=True, default='[[0,0,0,0]]', max_length=1024, null=True),
        ),
    ]
