# Generated by Django 2.2 on 2021-06-08 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_app', '0007_auto_20210606_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveaccrualpolicy',
            name='policy_type',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
